name: Run Lichess Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Stockfish
        run: |
          sudo apt-get update
          sudo apt-get install -y stockfish

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Start bot
        run: python bot.py
        env:
          LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN }}
          STOCKFISH_PATH: /usr/games/stockfish
